# --- !Ups
# CREATE TABLE USER(
#   USER_ID BIGINT(20) NOT NULL AUTO_INCREMENT,
#   USER_NAME VARCHAR(255) NOT NULL,
#   EMAIL VARCHAR(255) NOT NULL,
#   PASSWORD VARCHAR(255) NOT NULL,
#   PRIMARY KEY (USER_ID)
# ) DEFAULT CHARSET=utf8;
#
# INSERT INTO USER (USER_ID,USER_NAME,EMAIL, PASSWORD) VALUES ('1','natsumi','aaa@gamail.com', '0000');
#
# CREATE TABLE TWEET(
#   TWEET_ID BIGINT(20) NOT NULL AUTO_INCREMENT,
#   USER_NAME VARCHAR(255) NOT NULL,
#   CONTENT VARCHAR(255) NOT NULL,
#   IMAGE VARCHAR(255) NOT NULL,
#   DATE DATE NOT NULL,
#   PRIMARY KEY (TWEET_ID)
# ) DEFAULT CHARSET=utf8;









# --- !Downs
#DROP TABLE ACCOUNT;